### ISSUE TITLE
[Question] WHD

### ISSUE THREAD

**Issue by shabbirkagalwala** [solarwinds/containers#12]
Will there be an release for an updated Docker image for WHD 12.5.2 ?

**Comment by leecalcote** [comment]
Hi @shabbirkagalwala, great question. Yes, we'll go ahead and update to 12.5.2. If you're inclined to update and PR, we'd welcome this way forward as well.

**Comment by shabbirkagalwala** [comment]
@leecalcote Sure I can do that, I will add a PR by the end of this week.

**Comment by turbo** [comment]
Closing, because done. 

Note: Containers are going to be upgraded this week (WHD to 12.6). Changes are going to be included in the release notes.
