### ISSUE TITLE
agent-daemonset-1.8.yaml  refferes to namespace cnpt which does not exist

### ISSUE THREAD

**Issue by archyufa** [solarwinds/containers#13]
Minor issue with agent-daemonset-1.8.yaml manifest where it it points namespace cnpt. However there is not step to create namespace and also other manifest not using this namespace. So would be great either create and use namespace for all or not use namespace at all.
Also would be good to add manifest for 1.9 release of K8s with v1 API version.

**Comment by leecalcote** [comment]
Thanks @archyufa! PR #14 should fix.
