### ISSUE TITLE
WHD Insecure Port Override?

### ISSUE THREAD

**Issue by cshanepierce** [solarwinds/containers#2]
![whd-port-insecure](https://cloud.githubusercontent.com/assets/5185292/24925003/713ff1d0-1ebc-11e7-9929-443b7729db2d.jpg)

We are having an issue where we cannot change the WHD Insecure Port in the GUI as shown in the image above. Our setup is that a proxy communicates with the user over port 80, and the proxy communicates with the container on port 8081. We have found two work-arounds:

1. To build our own image overriding the $URL_DEFAULT_PORT logic in the whd_bin file.
2. To uncomment and update the $URL_DEFAULT_PORT attribute in the whd.conf file once docker run is executed. 

Is there a flag we can use when executing the docker run or docker service create that would allow us to keep from the above mentioned work-arounds?

**Comment by leecalcote** [comment]
@cshanepierce great question. You've correctly identified the appropriate parameter to override/supply with the port of your choice - $URL_DEFAULT_PORT.

We've [added documentation to highlight](https://github.com/solarwinds/containers/tree/master/whd#running-behind-a-proxy) a third option, using the _-e_ flag when initializing the WHD container.
